GET https://rest-api-deploy-production-4379.up.railway.app/movies

HTTP/1.1 200  - OK
access-control-allow-origin: undefined
content-length: 4024
content-type: application/json; charset=utf-8
date: Wed, 30 Apr 2025 02:14:35 GMT
etag: W/"fb8-XLTdrSNKTsBfAiMOjB3qDTPapsw"
server: railway-edge
x-railway-edge: railway/us-west1
x-railway-request-id: cl8ulwvnROaNPcsiv6JxzA_2395810083
connection: close