GET https://rest-api-deploy-xf6e.onrender.com/movies

HTTP/1.1 200  - OK
date: Fri, 02 May 2025 15:42:50 GMT
content-type: application/json; charset=utf-8
content-length: 352
connection: close
content-encoding: br
etag: W/"2e7-QO81oJvUulmQ++aKdLVASNUXuhQ"
rndr-id: e080e542-7502-46fa
vary: Origin, Accept-Encoding
x-render-origin-server: Render
cf-cache-status: DYNAMIC
server: cloudflare
cf-ray: 9398a1796d2db4cb-SCL
alt-svc: h3=":443"; ma=86400
###
GET https://rest-api-deploy-xf6e.onrender.com/movies/78940913-26c8-11f0-b05b-cecd02c812d5

HTTP/1.1 200  - OK
date: Fri, 02 May 2025 15:43:12 GMT
content-type: application/json; charset=utf-8
content-length: 185
connection: close
content-encoding: br
etag: W/"ec-tVKOETgpE/3tvzKosvGFe3QGfoY"
rndr-id: 30ddc8f5-8fee-4ac4
vary: Origin, Accept-Encoding
x-render-origin-server: Render
cf-cache-status: DYNAMIC
server: cloudflare
cf-ray: 9398a2024a45e7a0-SCL
alt-svc: h3=":443"; ma=86400
###
GET https://rest-api-deploy-xf6e.onrender.com/movies?genre=action

HTTP/1.1 200  - OK
date: Fri, 02 May 2025 15:43:27 GMT
content-type: application/json; charset=utf-8
content-length: 291
connection: close
content-encoding: br
etag: W/"200-RsOAKl3EipYtbTtKp85KaMGJriU"
rndr-id: 4bdff3a3-7c67-4ee5
vary: Origin, Accept-Encoding
x-render-origin-server: Render
cf-cache-status: DYNAMIC
server: cloudflare
cf-ray: 9398a25f9e65a5f0-SCL
alt-svc: h3=":443"; ma=86400